### ISSUE TITLE
ERR_PACKAGE_PATH_NOT_EXPORTED when running ipfs-interop

### ISSUE THREAD

**Issue by iand** [ipfs/interop#480]
Installed using npm install -g ipfs-interop

Ran and got

```
09:47 $ ipfs-interop

> ipfs-interop@8.0.10 pretest
> aegir build --esm-tests
Error: Cannot find module 'ipfs-http-client'
```

Installed using npm install -g ipfs-http-client

Now I get 

```
09:53 $ ipfs-interop

> ipfs-interop@8.0.10 pretest
> aegir build --esm-tests

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /usr/local/lib/node_modules/ipfs-http-client/package.json
    at new NodeError (node:internal/errors:372:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:472:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:693:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ipfs-interop/.aegir.cjs:29:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
/usr/local/lib/node_modules/ipfs-interop/node_modules/aegir/src/config/user.js:150
    throw new Error('Error finding your config file.')
    ^
Error: Error finding your config file.
    at config (/usr/local/lib/node_modules/ipfs-interop/node_modules/aegir/src/config/user.js:150:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/ipfs-interop/node_modules/aegir/src/config/user.js:162:15)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ipfs-interop/node_modules/aegir/src/index.js:18:24)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
file:///usr/local/lib/node_modules/ipfs-interop/bin/ipfs-interop.js:17
    throw new Error(`Child process exited with code ${code}`)
    ^

Error: Child process exited with code 1
    at ChildProcess.<anonymous> (file:///usr/local/lib/node_modules/ipfs-interop/bin/ipfs-interop.js:17:11)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
````

I'm not sure how to resolve.

**Comment by SgtPooki** [comment]
getting this same error when I run without first running `npm install` on this package's source. running `npm install` resolves that error, but then I get another [Error: No binary available for platform 'darwin' and arch 'undefined']()
