### ISSUE TITLE
files interop tests currently failing

### ISSUE THREAD

**Issue by alanshaw** [ipfs/interop#50]
Using js-ipfs master we're getting failures reading files and directories that do not exist. The error message has changed.

```console
 1) files
       returns an error when reading non-existent files:

      AssertionError: expected { Object (message, code) } to deeply equal { Object (message, code) }
      + expected - actual

       {
         "code": 0
      -  "message": "file does not exist"
      +  "message": "/i-do-not-exist-0.7005556072496701 does not exist"
       }
      
      at results.forEach.res (test/files.js:93:50)
      at Array.forEach (<anonymous>)
      at Promise.all.then.results (test/files.js:93:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) files
       returns an error when writing deeply nested files and the parents do not exist:

      AssertionError: expected { Object (message, code) } to deeply equal { Object (message, code) }
      + expected - actual

       {
         "code": 0
      -  "message": "file does not exist"
      +  "message": "directory does not exist"
       }
      
      at results.forEach.res (test/files.js:93:50)
      at Array.forEach (<anonymous>)
      at Promise.all.then.results (test/files.js:93:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

cc @achingbrain

**Comment by achingbrain** [comment]
We probably want to make the tests less strict here.

```
"file does not exist"
"/i-do-not-exist-0.7005556072496701 does not exist"
```

The first error is returned by `go-ipfs`, the second is by `js-ipfs` and is (I think) more useful to the user.

```
"file does not exist"
"directory does not exist"
```

Similar thing here - the error is caused by the intermediate directories not existing, so the second error is more expressive of the actual problem (though could include the directory path).

What do you think?

**Comment by alanshaw** [comment]
I agree the message is more descriptive on the JS IPFS side. Testing for "does not exist" in the message is good enough!

**Comment by alanshaw** [comment]
fixed by https://github.com/ipfs/interop/pull/51/commits/7c74643e41143c6779f043ecf9e4a87d0ee5362b in https://github.com/ipfs/interop/pull/51
