### ISSUE TITLE
files tests failing

### ISSUE THREAD

**Issue by Stebalien** [ipfs/interop#75]
```
files
    ✓ returns an error when reading non-existent files
    ✓ returns an error when writing deeply nested files and the parents do not exist
    1) uses raw nodes for leaf data
    ✓ errors when creating the same directory twice
    ✓ does not error when creating the same directory twice and -p is passed
    ✓ errors when creating the root directory
    has the same hashes for
      ✓ empty files (44ms)
      ✓ small files
      ✓ big files (114ms)
      ✓ files that have had data appended
      ✓ files that have had data overwritten
      - small files with CIDv1
      - big files with CIDv1
      ✓ trickle DAGs (3326ms)
      ✓ hamt shards (1858ms)
      2) updating mfs hamt shards
```

```
  1) files
       uses raw nodes for leaf data:
     TypeError: Cannot read property 'length' of undefined
      at Object.decode (node_modules/protons/src/compile/decode.js:80:17)
      at Function.Data.unmarshal (node_modules/ipfs-unixfs/src/index.js:101:30)
      at daemon.api.object.get.then.node (test/files.js:26:27)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) files
       has the same hashes for
         updating mfs hamt shards:
     TypeError: Cannot read property 'length' of undefined
      at Object.decode (node_modules/protons/src/compile/decode.js:80:17)
      at Function.Data.unmarshal (node_modules/ipfs-unixfs/src/index.js:101:30)
      at testHamtShardHashesAreEqual (test/files.js:382:29)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

Test run: https://circleci.com/gh/ipfs/go-ipfs/16697?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Stebalien** [comment]
I'm not seeing this anymore.
